### PR TITLE
Added german translations

### PR DESCRIPTION
**Pull request by mdittberner**
Added german translation pack based on Jesse's existing translations until 2017 and the new added labels until 2018-3.

### CODE REVIEW

**Comment by Seb33300** [comment]
Thank for your contribution.

I have merged your pull request, but I just see that you added the `next_id` key which not exists in the english translation:
https://github.com/FusionInvoice/translations/blob/master/de/fi.php#L264

Why?

**Comment by mdittberner** [comment]
Hi Sébastien,

I took all existing labels in the old core version of the german 
translation pack and added the new ones. Indeed I did not check if there 
are labels which have been removed. I remember that there was a field 
where you could set the next invoice ID (since the ID is increasing 
automatically this was sometimes useful). Indeed I miss this feature in 
Version 2018-3. So feel free to delete next_id if its not needed.

Regards,
Michael

-------------------------------------
Michael Dittberner
Dipl.-Ing. (FH) für Medientechnik
Certified TYPO3 CMS Integrator
Schiebestraße 32
04129 Leipzig
Tel.:     0341/2486008
E-Mail:   dittberner@klickkontakt.net
Internet: http://www.klickkontakt.net


Am 27.03.2018 um 13:50 schrieb Sébastien ALFAIATE:

**Comment by mdittberner** [comment]
Found it. "next_id" is still in use, so leave it.
You find it in the Setting for group records 
(http://www.yourdomain/groups) which are assigned to the invoices via 
invoiceGroup.

Regards,
Michael




Am 27.03.2018 um 14:31 schrieb Michael Dittberner:

**Comment by Seb33300** [comment]
I can only find `Next number` which is associated to the `next_number` key: https://demo.fusioninvoice.com/groups

Nothing about `next_id`.

**Pull request merged**
