### PR TITLE
Fixes de

### PR DESCRIPTION
**Pull request by mdittberner**
Fixed typos and removed old next_id label

### CODE REVIEW

**Comment by mdittberner** [comment]
Did it.



Am 29.03.2018 um 10:18 schrieb Sébastien ALFAIATE:

**Comment by Seb33300** [comment]
Dis you click on `Propose file change` after modifying the file?
Because I didn't receive your request.

**Comment by mdittberner** [comment]
Yes, I did and left a comment. It's in patch 2:
https://github.com/mdittberner/translations/tree/patch-2




Am 29.03.2018 um 10:43 schrieb Sébastien ALFAIATE:

**Comment by Seb33300** [comment]
Done.

This was because you didn't created a pull request from your patch-2 branch.
I created it and merged it here: https://github.com/FusionInvoice/translations/pull/3

**Comment by mdittberner** [comment]
Ah, ok. Thank you.




Am 29.03.2018 um 11:04 schrieb Sébastien ALFAIATE:

**Pull request closed without merging**
